// Imagine IF — content data
// Three rails of freedom tech: Intelligence (AI) · Humanity (Energy) · Money (Bitcoin)
window.IF_DATA = {
  event: {
    name: 'Imagine IF',
    year: '2026',
    dates: 'October 5–6, 2026',
    datesShort: 'Oct 5–6, 2026',
    venue: 'Fisher Center for the Performing Arts',
    venueCity: 'Nashville, TN',
    stages: ['Main Theatre', 'Second Stage'],
    days: ['Monday Oct 5', 'Tuesday Oct 6'],
  },

  // 9 confirmed today (synced with imagineifnashville.com); + TBA placeholder.
  // tags use three-rails framing: Intelligence / Humanity / Money / Freedom Tech.
  speakers: [
    { id: 'cathie-wood', name: 'Cathie Wood', role: 'Founder, CEO, and CIO', org: 'ARK Invest', tags: ['Money', 'Intelligence'], featured: true,
      photo: 'uploads/speakers/cathie-wood.png',
      bio: 'Cathie founded ARK to invest in disruptive innovation — genomics, robotics, AI, blockchain. She thinks in decades, not quarters.',
      talk: 'Imagine IF… capital flowed toward the future, not the past.' },
    { id: 'art-laffer', name: 'Dr. Art Laffer', role: 'Founder and Chairman', org: 'Laffer Associates', tags: ['Money'], featured: true,
      photo: 'uploads/speakers/art-laffer.png',
      bio: 'Architect of supply-side economics. Curious about what the next century of money looks like.',
      talk: 'Imagine IF… we taxed nothing we wanted more of.' },
    { id: 'scott-harrison', name: 'Scott Harrison', role: 'Founder and CEO', org: 'charity: water', tags: ['Humanity', 'Money'], featured: true,
      photo: 'uploads/speakers/scott-harrison.jpg',
      bio: 'Built one of the most trusted nonprofits in the world. Over $1 billion raised, 19 million people brought clean water. Storytelling is the missing skill in technical movements.',
      talk: 'Imagine IF… every dollar reached the person it was meant for.' },
    { id: 'jeff-booth', name: 'Jeff Booth', role: 'Author & Entrepreneur', org: 'The Price of Tomorrow', tags: ['Money', 'Intelligence'], featured: true,
      photo: 'uploads/speakers/jeff-booth.jpg',
      bio: 'Tech founder turned investor and author. Argues deflation is the natural state of progress and Bitcoin is the rails for it.',
      talk: 'Imagine IF… abundance was the default.' },
    { id: 'alex-gladstein', name: 'Alex Gladstein', role: 'Chief Strategy Officer', org: 'Human Rights Foundation', tags: ['Freedom Tech', 'Money'], featured: true,
      photo: 'uploads/speakers/alex-gladstein.jpg',
      bio: 'Champions Bitcoin as a tool for human rights. Documents how authoritarian regimes weaponize money — and how open networks fight back.',
      talk: 'Imagine IF… every human had a way out.' },
    { id: 'hash-hashemian', name: 'Hash Hashemian', role: 'President', org: 'American Nuclear Society', tags: ['Humanity'],
      photo: 'uploads/speakers/hash-hashemian.jpg',
      bio: 'Senior nuclear authority and AMS Corporation president. Working at the intersection of grid infrastructure, nuclear power, and the next-decade energy buildout.',
      talk: 'Imagine IF… atoms came back to the grid edge.' },
    { id: 'gideon-powell', name: 'Gideon Powell', role: 'CEO', org: 'Cholla Inc.', tags: ['Humanity', 'Money'],
      photo: 'uploads/speakers/gideon-powell.webp',
      bio: 'West Texas energy entrepreneur turning stranded gas into computation. Where the oil patch meets the bitcoin block.',
      talk: 'Imagine IF… we stopped flaring the future.' },
    { id: 'obi-nwosu', name: 'Obi Nwosu', role: 'CEO', org: 'Fedi', tags: ['Money', 'Humanity'],
      photo: 'uploads/speakers/obi-nwosu.webp',
      bio: 'Building federated mints so bitcoin actually works for the seven billion people who are not American institutional investors.',
      talk: 'Imagine IF… bitcoin came home to the village.' },
    { id: 'joe-liemandt', name: 'Joe Liemandt', role: 'Principal', org: 'Alpha School', tags: ['Intelligence', 'Humanity'], featured: true,
      photo: 'uploads/speakers/joe-liemandt.jpg',
      bio: 'Self-taught founder of one of the largest private software portfolios in the world. Now building AI-native schools at Alpha School.',
      talk: 'Imagine IF… every great idea found its team.' },
    { id: 'harry-sudock', name: 'Harry Sudock', role: 'Chief Business Officer', org: 'CleanSpark', tags: ['Money', 'Intelligence'],
      photo: 'uploads/speakers/harry-sudock.jpg',
      bio: 'Chief Business Officer at CleanSpark. Operating at the intersection of bitcoin mining and AI compute — a decade of behind-the-meter, megawatt-scale infrastructure that the hyperscalers are now scrambling to learn.',
      talk: 'Imagine IF… miners built the AI cloud.' },
  ],

  sponsors: {
    presenting: [
      { name: 'Human Rights Foundation', short: 'HRF' },
    ],
    founding: [
      { name: 'Unchained' },
      { name: 'Fedi' },
      { name: 'Foundry' },
    ],
    pillar: [
      { name: 'ARK Invest' },
      { name: 'Cholla Inc.' },
      { name: 'CleanSpark' },
      { name: 'Proto' },
    ],
    supporting: [
      { name: 'Bitkey' },
    ],
  },

  // Agenda — not yet public. Will be added closer to the event.
  agenda: [],

  // Imagine IF 2025 archive — full YouTube playlist (PL2L0KLglmktkV95Iv6SAis4DsqoIROzJz)
  // Each talk: ten minutes, one idea. Thumbnails from img.youtube.com.
  pastTalks: [
    { year: '2025', videoId: '6bbtHYft7t8', title: 'Bitcoin Brainstorm', speakers: 'Cathie Wood, Sen. Bill Hagerty, Dr. Laffer, Rod Roudi, Odell, & Harry Sudock' },
    { year: '2025', videoId: '0PtYdjSXMFI', title: 'The Sovereign Yield Curve: Bitcoin, Bonds, and a New Credit Paradigm', speakers: '' },
    { year: '2025', videoId: 'MCU81VGn2Kw', title: "Imagine IF We Didn't Fear Innovation", speakers: 'Troy Cross' },
    { year: '2025', videoId: 'YE6Ck4eKgp4', title: 'Imagine IF America Leads', speakers: 'Rod Roudi & Tennessee AG Jonathan Skrmetti' },
    { year: '2025', videoId: 'xfqFS-IVOog', title: 'Super Collateral for a Compute Based World: Bitcoin, AI, and Energy', speakers: 'Grant Gilliam & Sean Bill' },
    { year: '2025', videoId: 'apvU3H4IUMs', title: 'What Proof of Work Proves', speakers: 'Parker Lewis & Rapha Zagury' },
    { year: '2025', videoId: '9b-H7FFzayE', title: 'Heat as Freedom Technology: Decentralizing Mining Through Energy Use', speakers: 'Tyler Stevens' },
    { year: '2025', videoId: 'T7IbOJQ-kes', title: 'Does Cypherpunk Scale? (Does It Have To?)', speakers: 'Ryan Gentry, Jay Beddict, D++, & Uncle Rockstar Dev' },
    { year: '2025', videoId: '3QpPva8ygAU', title: "Imagine IF the American Nuclear Renaissance Isn't Just a Talking Point", speakers: '' },
    { year: '2025', videoId: 'uv_lWfRE-wo', title: 'How Do You Hold the Revolution?', speakers: 'Stephan Livera & Joe Kelly' },
    { year: '2025', videoId: 'LMypUHKirTI', title: 'Winning the Race for Freedom: Geopolitics in the Age of Digital Disruption', speakers: 'Matt Pines' },
    { year: '2025', videoId: 'NPGF-X1qY44', title: '2140: What Changes? What Stays the Same?', speakers: 'Michael Goldstein & Adam Back' },
    { year: '2025', videoId: 'hByt68km8C4', title: 'No Innovation is an Island', speakers: 'Robert Warren, Skot9000, Brady Cuddy, & Philip Walton' },
    { year: '2025', videoId: 'ZkYSy5y39cE', title: 'Why First Principles Still Matter in the Digital World', speakers: 'Matt Schulz & Sen. Marsha Blackburn' },
    { year: '2025', videoId: 'LyBrvnwARlk', title: 'Freedom of Thought in the Age of AI', speakers: 'Mark Suman' },
    { year: '2025', videoId: 'JLcRUS-a4_g', title: 'Master to Student, the Supply Side Economy', speakers: 'Cathie Wood & Dr. Art Laffer' },
    { year: '2025', videoId: 'nW_3jppA9nQ', title: "The Emergent Grid: Lessons From Africa for America's Energy Future", speakers: 'Erik Hersman' },
    { year: '2025', videoId: 'qvTx84brNt0', title: 'Closing Panel', speakers: 'Rod Roudi, Robert Warren, D++, & Anna Checkhovich' },
    { year: '2025', videoId: 'rFV8CfFF5kg', title: 'Trust Nobody, Ever Again — Building a Modular Future', speakers: 'John Arnold, Max Kei, & Rory Murray' },
    { year: '2025', videoId: '7eFb7AQla_k', title: 'Making Freedom Profitable', speakers: 'Matt Odell' },
    { year: '2025', videoId: 'Rs1y1gEAwNU', title: 'Energy as a Balance Sheet', speakers: 'Robert Warren & Adam Sullivan' },
    { year: '2025', videoId: 'NObq313h0hc', title: 'Bitcoin as Constitutional Order: Stories that Become States', speakers: 'Jonathan Kirkwood & Brian Domitrovic' },
    { year: '2025', videoId: 'URbBq6C4PE8', title: 'Local Power, Global Fuel: Securing Energy Independence', speakers: '' },
    { year: '2025', videoId: 'V-f8JFhbW4E', title: 'The Frontier Playbook for Ambition', speakers: 'Harry Sudock' },
    { year: '2025', videoId: '4OZcEgX4ZvE', title: 'Welcome to Nashville + Partnership 2030', speakers: 'Stephanie Coleman' },
    { year: '2025', videoId: 'B90AG3sHJ2E', title: 'Speed to Scale and the New Era of Compute', speakers: 'Harry Sudock, Adam Sullivan, & Kara Sutton' },
    { year: '2025', videoId: 'hfXUwuH2OPU', title: 'Freedom Tech is Fundamental to a Free Society', speakers: 'Econoalchemist' },
    { year: '2025', videoId: 'kbMfJtEHHLQ', title: 'Open Communities in the Age of Control', speakers: 'Matt Odell, Derek Ross, & Shawn Yeager' },
    { year: '2025', videoId: 'ksXNu8tKm1A', title: 'ImagineIF: The Summit of Summits', speakers: '' },
  ],
};
