// Imagine IF — content data
// Three rails of freedom tech: Intelligence (AI) · Humanity (Energy) · Money (Bitcoin)
window.IF_DATA = {
  event: {
    name: 'Imagine IF',
    year: '2026',
    dates: 'October 5–6, 2026',
    datesShort: 'Oct 5–6, 2026',
    venue: 'Fisher Center for the Performing Arts',
    venueCity: 'Nashville, TN',
    stages: ['Main Theatre', 'Second Stage'],
    days: ['Monday Oct 5', 'Tuesday Oct 6'],
  },

  // 9 confirmed today (synced with imagineifnashville.com); + TBA placeholder.
  // tags use three-rails framing: Intelligence / Humanity / Money / Freedom Tech.
  speakers: [
    { id: 'cathie-wood', name: 'Cathie Wood', role: 'Founder, CEO, and CIO', org: 'ARK Invest', tags: ['Money', 'Intelligence'], featured: true,
      photo: 'uploads/speakers/cathie-wood.png',
      x: 'https://x.com/CathieDWood',
      linkedin: 'https://www.linkedin.com/in/catherinedwood/',
      bio: 'Cathie founded ARK to invest in disruptive innovation — genomics, robotics, AI, blockchain. She thinks in decades, not quarters.',
      talk: 'Imagine IF… capital flowed toward the future, not the past.' },
    { id: 'art-laffer', name: 'Dr. Art Laffer', role: 'Founder and Chairman', org: 'Laffer Associates', tags: ['Money'], featured: true,
      photo: 'uploads/speakers/art-laffer.png',
      x: 'https://x.com/realartlaffer',
      bio: 'Architect of supply-side economics. Curious about what the next century of money looks like.',
      talk: 'Imagine IF… we taxed nothing we wanted more of.' },
    { id: 'scott-harrison', name: 'Scott Harrison', role: 'Founder and CEO', org: 'charity: water', tags: ['Humanity', 'Money'], featured: true,
      photo: 'uploads/speakers/scott-harrison.jpg',
      x: 'https://x.com/scottharrison',
      linkedin: 'https://www.linkedin.com/in/scottharrison1/',
      bio: 'Built one of the most trusted nonprofits in the world. Over $1 billion raised, 19 million people brought clean water. Storytelling is the missing skill in technical movements.',
      talk: 'Imagine IF… every dollar reached the person it was meant for.' },
    { id: 'jeff-booth', name: 'Jeff Booth', role: 'Author & Entrepreneur', org: 'The Price of Tomorrow', tags: ['Money', 'Intelligence'], featured: true,
      photo: 'uploads/speakers/jeff-booth.jpg',
      x: 'https://x.com/JeffBooth',
      linkedin: 'https://www.linkedin.com/in/jeffdbooth/',
      bio: 'Tech founder turned investor and author. Argues deflation is the natural state of progress and Bitcoin is the rails for it.',
      talk: 'Imagine IF… abundance was the default.' },
    { id: 'alex-gladstein', name: 'Alex Gladstein', role: 'Chief Strategy Officer', org: 'Human Rights Foundation', tags: ['Freedom Tech', 'Money'], featured: true,
      photo: 'uploads/speakers/alex-gladstein.jpg',
      photoPos: 'center 35%',
      x: 'https://x.com/gladstein',
      linkedin: 'https://www.linkedin.com/in/alexgladstein/',
      bio: 'Champions Bitcoin as a tool for human rights. Documents how authoritarian regimes weaponize money — and how open networks fight back.',
      talk: 'Imagine IF… every human had a way out.' },
    { id: 'melissa-mahtani', name: 'Melissa Mahtani', role: 'Journalist-in-Residence', org: 'AI Lab', tags: ['Intelligence', 'Freedom Tech'],
      photo: 'uploads/speakers/melissa-mahtani.png',
      linkedin: 'https://www.linkedin.com/in/melissa-mahtani/',
      bio: 'International journalist, anchor, and moderator focused on emerging technology, human rights, and equality. Journalist-in-residence at AI Lab and host of the AI Lab Podcast; previously executive producer of CBS News Confirmed and senior producer/reporter at CNN.',
      talk: 'Imagine IF… truth kept pace with technology.' },
    { id: 'hash-hashemian', name: 'Hash Hashemian', role: 'President', org: 'American Nuclear Society', tags: ['Humanity'],
      photo: 'uploads/speakers/hash-hashemian.jpg',
      bio: 'Senior nuclear authority and AMS Corporation president. Working at the intersection of grid infrastructure, nuclear power, and the next-decade energy buildout.',
      talk: 'Imagine IF… atoms came back to the grid edge.' },
    { id: 'gideon-powell', name: 'Gideon Powell', role: 'CEO', org: 'Cholla Inc.', tags: ['Humanity', 'Money'],
      photo: 'uploads/speakers/gideon-powell.webp',
      x: 'https://x.com/GideonOPowell',
      linkedin: 'https://www.linkedin.com/in/gideon-o-powell-%F0%9F%8F%B4%E2%80%8D%E2%98%A0%EF%B8%8F-84615a50/',
      bio: 'West Texas energy entrepreneur turning stranded gas into computation. Where the oil patch meets the bitcoin block.',
      talk: 'Imagine IF… we stopped flaring the future.' },
    { id: 'obi-nwosu', name: 'Obi Nwosu', role: 'CEO', org: 'Fedi', tags: ['Money', 'Humanity'],
      photo: 'uploads/speakers/obi-nwosu.webp',
      x: 'https://x.com/obi',
      linkedin: 'https://uk.linkedin.com/in/obinwosu',
      bio: 'Building federated mints so bitcoin actually works for the seven billion people who are not American institutional investors.',
      talk: 'Imagine IF… bitcoin came home to the village.' },
    { id: 'joe-liemandt', name: 'Joe Liemandt', role: 'Principal', org: 'Alpha School', tags: ['Intelligence', 'Humanity'], featured: true,
      photo: 'uploads/speakers/joe-liemandt.jpg',
      photoPos: 'center 30%',
      x: 'https://x.com/jliemandt',
      linkedin: 'https://www.linkedin.com/in/liemandt/',
      bio: 'Self-taught founder of one of the largest private software portfolios in the world. Now building AI-native schools at Alpha School.',
      talk: 'Imagine IF… every great idea found its team.' },
    { id: 'harry-sudock', name: 'Harry Sudock', role: 'Chief Business Officer', org: 'CleanSpark', tags: ['Money', 'Intelligence'],
      photo: 'uploads/speakers/harry-sudock.jpg',
      x: 'https://x.com/harry_sudock',
      linkedin: 'https://www.linkedin.com/in/harrysudock/',
      bio: 'Chief Business Officer at CleanSpark. Operating at the intersection of bitcoin mining and AI compute — a decade of behind-the-meter, megawatt-scale infrastructure that the hyperscalers are now scrambling to learn.',
      talk: 'Imagine IF… miners built the AI cloud.' },
    { id: 'parker-lewis', name: 'Parker Lewis', role: 'Author, Gradually Then Suddenly', org: 'Zaprite', tags: ['Money'],
      photo: 'uploads/speakers/parker-lewis.jpg',
      x: 'https://x.com/parkeralewis',
      linkedin: 'https://www.linkedin.com/in/parker-lewis-ab904669/',
      bio: 'One of the most consistent intellectual voices on bitcoin as monetary infrastructure. Author of the "Gradually, Then Suddenly" essay series — the book the rest of bitcoin keeps catching up to. Head of Business Development at Zaprite.',
      talk: 'Imagine IF… every saver became a builder.' },
    { id: 'andre-neves', name: 'Andre Neves', role: 'CTO & Co-Founder', org: 'ZBD', tags: ['Money'],
      photo: 'uploads/speakers/andre-neves.jpg',
      x: 'https://x.com/andreneves',
      linkedin: 'https://www.linkedin.com/in/andrerfneves',
      bio: 'CTO and co-founder of ZBD. Co-author of the Lightning Address protocol — the email-style identifier that lets anyone send and receive bitcoin without a wallet address. Building the rails that make bitcoin payments feel like the internet.',
      talk: 'Imagine IF… bitcoin felt as easy as email.' },
    { id: 'stephanie-coleman', name: 'Stephanie Coleman', role: 'President & CEO', org: 'Nashville Area Chamber of Commerce', tags: ['Humanity'],
      photo: 'uploads/speakers/stephanie-coleman.jpg',
      x: 'https://x.com/fe3',
      linkedin: 'https://www.linkedin.com/in/stephanie-coleman-1956775/',
      bio: 'President and CEO of the Nashville Area Chamber of Commerce. Leading Partnership 2030 — the region\'s five-year economic strategy for community vitality, mobility, and character. Vanderbilt economist by training, Nashville builder by choice.',
      talk: 'Imagine IF… every city built itself on purpose.' },
    { id: 'rapha-zagury', name: 'Rapha Zagury', role: 'Founder & CEO', org: 'Elektron Energy', tags: ['Money', 'Humanity'],
      photo: 'uploads/speakers/rapha-zagury.jpg',
      x: 'https://x.com/alphazeta',
      linkedin: 'https://www.linkedin.com/in/rzagury/',
      bio: 'Founder and CEO of Elektron Energy — one of the largest bitcoin mining operators in the world. Previously CIO at Swan Bitcoin, MD at Deutsche Bank and Merrill Lynch, VP at Goldman Sachs. Built career-spanning expertise in capital markets and now applies it to the watt-as-product economy.',
      talk: 'Imagine IF… every watt knew its highest use.' },
    { id: 'alex-brammer', name: 'Alex Brammer', role: 'EVP of Operations', org: 'Keel Infrastructure', tags: ['Money'],
      photo: 'uploads/speakers/alex-brammer.jpg',
      x: 'https://x.com/AB_Brammer',
      linkedin: 'https://www.linkedin.com/in/alex-brammer/',
      bio: 'Leads global operations at Keel Infrastructure (NASDAQ: KEEL), scaling the megawatt-scale compute campuses where bitcoin mining and AI share the meter. Previously stood up the world\'s first nuclear-powered bitcoin mining datacenter at Talen Energy. Sixteen-year Army officer turned infrastructure operator.',
      talk: 'Imagine IF… every megawatt had a mission.' },
    { id: 'bill-hagerty', name: 'Bill Hagerty', role: 'U.S. Senator', org: 'Tennessee', tags: ['Money', 'Freedom Tech'],
      photo: 'uploads/speakers/bill-hagerty.png',
      x: 'https://x.com/SenatorHagerty',
      linkedin: 'https://www.linkedin.com/in/bill-hagerty-363876b4/',
      bio: 'Senator Bill Hagerty represents Tennessee in the United States Senate, where he advocates for pro-growth economic policies, technological innovation, and constitutional principles. As a former businessman and U.S. Ambassador to Japan, Senator Hagerty brings unique insights into international trade, economic development, and the intersection of policy and technology. His perspective on regulatory frameworks, economic freedom, and technological advancement provides valuable insights for discussions about Bitcoin, AI, and emerging technologies.' },
    { id: 'paul-itoi', name: 'Paul Itoi', role: 'Founder & CEO', org: 'Stakwork', tags: ['Intelligence', 'Money'],
      photo: 'uploads/speakers/paul-itoi.png',
      x: 'https://x.com/paulitoi',
      bio: 'Founder and CEO of Stakwork — workflows where AI and humans split the work and get paid in bitcoin over Lightning. A driving force behind Sphinx, the open-source Lightning-powered communications platform. Tech entrepreneur since the mid-nineties, now building at the Bitcoin × AI frontier.',
      talk: 'Imagine IF… anyone, anywhere could earn in seconds.' },
  ],

  sponsors: {
    presenting: [
      // HRF temporarily hidden — keep entry handy for when it returns:
      // { name: 'Human Rights Foundation', short: 'HRF', url: 'https://hrf.org' },
    ],
    founding: [
      { name: 'Unchained', url: 'https://unchained.com' },
      { name: 'Fedi', url: 'https://www.fedi.xyz' },
      { name: 'Foundry', url: 'https://www.foundrydigital.com' },
    ],
    pillar: [
      { name: 'ARK Invest', url: 'https://www.ark-invest.com' },
      { name: 'Cholla Inc.', url: 'https://chollainc.com' },
      { name: 'CleanSpark', url: 'https://www.cleanspark.com' },
      { name: 'Proto', url: 'https://proto.xyz/' },
    ],
    supporting: [
      { name: 'Bitkey', url: 'https://bitkey.world' },
    ],
  },

  // Agenda — not yet public. Will be added closer to the event.
  agenda: [],

  // Imagine IF 2025 archive — full YouTube playlist (PL2L0KLglmktkV95Iv6SAis4DsqoIROzJz)
  // Each talk: ten minutes, one idea. Thumbnails from img.youtube.com.
  // Order: Master-to-Student fireside (Cathie + Laffer) → all "Imagine IF" titled talks → rest.
  pastTalks: [
    // Master to Student first
    { year: '2025', videoId: 'JLcRUS-a4_g', title: 'Master to Student, the Supply Side Economy', speakers: 'Cathie Wood & Dr. Art Laffer' },

    // "Imagine IF…" titled talks
    { year: '2025', videoId: 'MCU81VGn2Kw', title: "Imagine IF We Didn't Fear Innovation", speakers: 'Troy Cross' },
    { year: '2025', videoId: 'YE6Ck4eKgp4', title: 'Imagine IF America Leads', speakers: 'Rod Roudi & Tennessee AG Jonathan Skrmetti' },
    { year: '2025', videoId: '3QpPva8ygAU', title: "Imagine IF the American Nuclear Renaissance Isn't Just a Talking Point", speakers: '' },
    { year: '2025', videoId: 'ksXNu8tKm1A', title: 'ImagineIF: The Summit of Summits', speakers: '' },

    // Rest of the archive
    { year: '2025', videoId: '6bbtHYft7t8', title: 'Bitcoin Brainstorm', speakers: 'Cathie Wood, Sen. Bill Hagerty, Dr. Laffer, Rod Roudi, Odell, & Harry Sudock' },
    { year: '2025', videoId: '0PtYdjSXMFI', title: 'The Sovereign Yield Curve: Bitcoin, Bonds, and a New Credit Paradigm', speakers: '' },
    { year: '2025', videoId: 'xfqFS-IVOog', title: 'Super Collateral for a Compute Based World: Bitcoin, AI, and Energy', speakers: 'Grant Gilliam & Sean Bill' },
    { year: '2025', videoId: 'apvU3H4IUMs', title: 'What Proof of Work Proves', speakers: 'Parker Lewis & Rapha Zagury' },
    { year: '2025', videoId: '9b-H7FFzayE', title: 'Heat as Freedom Technology: Decentralizing Mining Through Energy Use', speakers: 'Tyler Stevens' },
    { year: '2025', videoId: 'T7IbOJQ-kes', title: 'Does Cypherpunk Scale? (Does It Have To?)', speakers: 'Ryan Gentry, Jay Beddict, D++, & Uncle Rockstar Dev' },
    { year: '2025', videoId: 'uv_lWfRE-wo', title: 'How Do You Hold the Revolution?', speakers: 'Stephan Livera & Joe Kelly' },
    { year: '2025', videoId: 'LMypUHKirTI', title: 'Winning the Race for Freedom: Geopolitics in the Age of Digital Disruption', speakers: 'Matt Pines' },
    { year: '2025', videoId: 'NPGF-X1qY44', title: '2140: What Changes? What Stays the Same?', speakers: 'Michael Goldstein & Adam Back' },
    { year: '2025', videoId: 'hByt68km8C4', title: 'No Innovation is an Island', speakers: 'Robert Warren, Skot9000, Brady Cuddy, & Philip Walton' },
    { year: '2025', videoId: 'ZkYSy5y39cE', title: 'Why First Principles Still Matter in the Digital World', speakers: 'Matt Schulz & Sen. Marsha Blackburn' },
    { year: '2025', videoId: 'LyBrvnwARlk', title: 'Freedom of Thought in the Age of AI', speakers: 'Mark Suman' },
    { year: '2025', videoId: 'nW_3jppA9nQ', title: "The Emergent Grid: Lessons From Africa for America's Energy Future", speakers: 'Erik Hersman' },
    { year: '2025', videoId: 'qvTx84brNt0', title: 'Closing Panel', speakers: 'Rod Roudi, Robert Warren, D++, & Anna Checkhovich' },
    { year: '2025', videoId: 'rFV8CfFF5kg', title: 'Trust Nobody, Ever Again — Building a Modular Future', speakers: 'John Arnold, Max Kei, & Rory Murray' },
    { year: '2025', videoId: '7eFb7AQla_k', title: 'Making Freedom Profitable', speakers: 'Matt Odell' },
    { year: '2025', videoId: 'Rs1y1gEAwNU', title: 'Energy as a Balance Sheet', speakers: 'Robert Warren & Adam Sullivan' },
    { year: '2025', videoId: 'NObq313h0hc', title: 'Bitcoin as Constitutional Order: Stories that Become States', speakers: 'Jonathan Kirkwood & Brian Domitrovic' },
    { year: '2025', videoId: 'URbBq6C4PE8', title: 'Local Power, Global Fuel: Securing Energy Independence', speakers: '' },
    { year: '2025', videoId: 'V-f8JFhbW4E', title: 'The Frontier Playbook for Ambition', speakers: 'Harry Sudock' },
    { year: '2025', videoId: '4OZcEgX4ZvE', title: 'Welcome to Nashville + Partnership 2030', speakers: 'Stephanie Coleman' },
    { year: '2025', videoId: 'B90AG3sHJ2E', title: 'Speed to Scale and the New Era of Compute', speakers: 'Harry Sudock, Adam Sullivan, & Kara Sutton' },
    { year: '2025', videoId: 'hfXUwuH2OPU', title: 'Freedom Tech is Fundamental to a Free Society', speakers: 'Econoalchemist' },
    { year: '2025', videoId: 'kbMfJtEHHLQ', title: 'Open Communities in the Age of Control', speakers: 'Matt Odell, Derek Ross, & Shawn Yeager' },
  ],
};
