// Imagine IF — content data
// Three rails of freedom tech: Intelligence (AI) · Humanity (Energy) · Money (Bitcoin)
window.IF_DATA = {
  event: {
    name: 'Imagine IF',
    year: '2026',
    dates: 'October 5–6, 2026',
    datesShort: 'Oct 5–6, 2026',
    venue: 'Fisher Center for the Performing Arts',
    venueCity: 'Nashville, TN',
    stages: ['Main Theatre', 'Second Stage'],
    days: ['Monday Oct 5', 'Tuesday Oct 6'],
  },

  // Confirmed speaker slate; + TBA placeholder.
  // tags use three-rails framing: Intelligence / Humanity / Money / Freedom Tech.
  speakers: [
    { id: 'cathie-wood', name: 'Cathie Wood', role: 'Founder, CEO, and CIO', org: 'ARK Invest', tags: ['Money', 'Intelligence'], featured: true,
      photo: 'uploads/speakers/cathie-wood.png',
      x: 'https://x.com/CathieDWood',
      linkedin: 'https://www.linkedin.com/in/catherinedwood/',
      bio: 'Cathie founded ARK to invest in disruptive innovation — genomics, robotics, AI, blockchain. She thinks in decades, not quarters.',
      talk: 'Imagine IF… capital flowed toward the future, not the past.' },
    { id: 'art-laffer', name: 'Dr. Art Laffer', role: 'Founder and Chairman', org: 'Laffer Associates', tags: ['Money'], featured: true,
      photo: 'uploads/speakers/art-laffer.png',
      x: 'https://x.com/realartlaffer',
      bio: 'Architect of supply-side economics. Curious about what the next century of money looks like.',
      talk: 'Imagine IF… we taxed nothing we wanted more of.' },
    { id: 'sean-james', name: 'Sean James', role: 'Distinguished Engineer, Energy Systems', org: 'NVIDIA', tags: ['Humanity', 'Intelligence'], featured: true,
      photo: 'uploads/speakers/sean-james.jpg',
      photoPos: 'center 30%',
      linkedin: 'https://www.linkedin.com/in/sean-james-6592524/',
      bio: 'At NVIDIA, Sean focuses on power, grid integration, and energy architecture for large-scale AI infrastructure and AI factories.\n\nSean works at the intersection of compute, power, and land, helping define how next-generation AI data centers secure energy, scale rapidly, and integrate with constrained electrical grids. His work spans high-density power architecture, grid-forming and behind-the-meter energy systems, battery energy storage, fuel cells, and strategies to accelerate time-to-power for AI deployments worldwide.\n\nBefore joining NVIDIA, Sean spent nearly two decades at Microsoft, where he held senior leadership roles in data center operations, construction, and technology commercialization. He led and scaled multiple next-generation data center programs, bridging early-stage R&D with production deployment across Microsoft\'s global cloud footprint.\n\nSean began his career in hands-on data center operations and previously served in the U.S. Navy Submarine Fleet as an electrician. He holds multiple patents related to data center and energy systems and a degree in Information Technology. He is a father of three sons.',
      talk: 'Imagine IF… data centers disappeared.' },
    { id: 'scott-harrison', name: 'Scott Harrison', role: 'Founder and CEO', org: 'charity: water', tags: ['Humanity', 'Money'], featured: true,
      photo: 'uploads/speakers/scott-harrison.jpg',
      x: 'https://x.com/scottharrison',
      linkedin: 'https://www.linkedin.com/in/scottharrison1/',
      bio: 'Built one of the most trusted nonprofits in the world. Over $1 billion raised, 19 million people brought clean water. Storytelling is the missing skill in technical movements.',
      talk: 'Imagine IF… every dollar reached the person it was meant for.' },
    { id: 'jeff-booth', name: 'Jeff Booth', role: 'Author & Entrepreneur', org: 'The Price of Tomorrow', tags: ['Money', 'Intelligence'],
      photo: 'uploads/speakers/jeff-booth.jpg',
      x: 'https://x.com/JeffBooth',
      linkedin: 'https://www.linkedin.com/in/jeffdbooth/',
      bio: 'Tech founder turned investor and author. Argues deflation is the natural state of progress and Bitcoin is the rails for it.',
      talk: 'Imagine IF… abundance was the default.' },
    { id: 'alex-gladstein', name: 'Alex Gladstein', role: 'Chief Strategy Officer', org: 'Human Rights Foundation', tags: ['Freedom Tech', 'Money'], featured: true,
      photo: 'uploads/speakers/alex-gladstein.jpg',
      photoPos: 'center 35%',
      x: 'https://x.com/gladstein',
      linkedin: 'https://www.linkedin.com/in/alexgladstein/',
      bio: 'Champions Bitcoin as a tool for human rights. Documents how authoritarian regimes weaponize money — and how open networks fight back.',
      talk: 'Imagine IF… every human had a way out.' },
    { id: 'bill-hagerty', name: 'Bill Hagerty', role: 'U.S. Senator', org: 'Tennessee', tags: ['Money', 'Freedom Tech'], featured: true,
      photo: 'uploads/speakers/bill-hagerty.png',
      x: 'https://x.com/SenatorHagerty',
      linkedin: 'https://www.linkedin.com/in/bill-hagerty-363876b4/',
      bio: 'Senator Bill Hagerty represents Tennessee in the United States Senate, where he advocates for pro-growth economic policies, technological innovation, and constitutional principles. As a former businessman and U.S. Ambassador to Japan, Senator Hagerty brings unique insights into international trade, economic development, and the intersection of policy and technology. His perspective on regulatory frameworks, economic freedom, and technological advancement provides valuable insights for discussions about Bitcoin, AI, and emerging technologies.' },
    { id: 'joe-liemandt', name: 'Joe Liemandt', role: 'Principal', org: 'Alpha School', tags: ['Intelligence', 'Humanity'], featured: true,
      photo: 'uploads/speakers/joe-liemandt.jpg',
      x: 'https://x.com/jliemandt',
      linkedin: 'https://www.linkedin.com/in/liemandt/',
      bio: 'Self-taught founder of one of the largest private software portfolios in the world. Now building AI-native schools at Alpha School.',
      talk: 'Imagine IF… every great idea found its team.' },
    { id: 'melissa-mahtani', name: 'Melissa Mahtani', role: 'Journalist-in-Residence', org: 'AI Lab', tags: ['Intelligence', 'Freedom Tech'],
      photo: 'uploads/speakers/melissa-mahtani.png',
      linkedin: 'https://www.linkedin.com/in/melissa-mahtani/',
      bio: 'International journalist, anchor, and moderator focused on emerging technology, human rights, and equality. Journalist-in-residence at AI Lab and host of the AI Lab Podcast; previously executive producer of CBS News Confirmed and senior producer/reporter at CNN.',
      talk: 'Imagine IF… truth kept pace with technology.' },
    { id: 'hash-hashemian', name: 'Hash Hashemian', role: 'President', org: 'American Nuclear Society', tags: ['Humanity'],
      photo: 'uploads/speakers/hash-hashemian.jpg',
      bio: 'Senior nuclear authority and AMS Corporation president. Working at the intersection of grid infrastructure, nuclear power, and the next-decade energy buildout.',
      talk: 'Imagine IF… atoms came back to the grid edge.' },
    { id: 'gideon-powell', name: 'Gideon Powell', role: 'CEO', org: 'Cholla Inc.', tags: ['Humanity', 'Money'],
      photo: 'uploads/speakers/gideon-powell.webp',
      x: 'https://x.com/GideonOPowell',
      linkedin: 'https://www.linkedin.com/in/gideon-o-powell-%F0%9F%8F%B4%E2%80%8D%E2%98%A0%EF%B8%8F-84615a50/',
      bio: 'West Texas energy entrepreneur turning stranded gas into computation. Where the oil patch meets the bitcoin block.',
      talk: 'Imagine IF… we stopped flaring the future.' },
    { id: 'obi-nwosu', name: 'Obi Nwosu', role: 'CEO', org: 'Fedi', tags: ['Money', 'Humanity'],
      photo: 'uploads/speakers/obi-nwosu.webp',
      x: 'https://x.com/obi',
      linkedin: 'https://uk.linkedin.com/in/obinwosu',
      bio: 'Building federated mints so bitcoin actually works for the seven billion people who are not American institutional investors.',
      talk: 'Imagine IF… bitcoin came home to the village.' },
    { id: 'paul-nakasone', name: 'General Paul M. Nakasone', role: 'Founding Director, Institute of National Security', org: 'Vanderbilt University', tags: ['Intelligence', 'Freedom Tech'],
      photo: 'uploads/speakers/paul-nakasone.jpg',
      photoPos: 'center 18%',
      bio: 'A retired four-star general from a family with three generations of Army service, Paul M. Nakasone dedicated nearly 40 years to the military, culminating as Director of the NSA and Commander of U.S. Cyber Command. He pioneered a strategy of persistent engagement and public-private partnerships to actively confront cyber adversaries, leading efforts to dismantle ISIS online, counter Iranian cyber threats, and protect allies like Ukraine from Russian malware.\n\nSince retiring, Paul has focused on shaping the next generation of national security leaders. He helped found the Institute of National Security at Vanderbilt University, emphasizing the need for professionals with expertise in technology, policy, and critical thinking — where future policymakers will code, and coders will understand policy.\n\nPaul serves on the Board of Directors for OpenAI, where he contributes his expertise to AI safety and security. He also serves on the boards of Neuberger Berman Mutual Funds and WitnessAI, and is a nationally recognized speaker on national security, disruptive technologies, and leadership.\n\nPaul earned a bachelor’s degree from Saint John’s University in Minnesota and graduate degrees from the University of Southern California, the National Defense Intelligence College, and the U.S. Army War College.',
      talk: 'Imagine IF… cyber defense moved at the speed of intelligence.' },
    { id: 'harry-sudock', name: 'Harry Sudock', role: 'Chief Business Officer', org: 'CleanSpark', tags: ['Money', 'Intelligence'],
      photo: 'uploads/speakers/harry-sudock.jpg',
      x: 'https://x.com/harry_sudock',
      linkedin: 'https://www.linkedin.com/in/harrysudock/',
      bio: 'Chief Business Officer at CleanSpark. Operating at the intersection of bitcoin mining and AI compute — a decade of behind-the-meter, megawatt-scale infrastructure that the hyperscalers are now scrambling to learn.',
      talk: 'Imagine IF… miners built the AI cloud.' },
    { id: 'nacho-pauls', name: 'Nacho Pauls', role: 'Chief Commercial Officer', org: 'OCEAN', tags: ['Money', 'Freedom Tech'],
      photo: 'uploads/speakers/nacho-pauls.png',
      linkedin: 'https://www.linkedin.com/in/nacho-pauls-67501b115/',
      bio: 'Chief Commercial Officer at OCEAN, the decentralized Bitcoin mining pool building tools for more transparent, permissionless mining. An Argentine-born bitcoin advocate and former athlete, Nacho works with miners to expand adoption of DATUM and strengthen the infrastructure layer that keeps Bitcoin open.',
      talk: 'Imagine IF… mining became permissionless again.' },
    { id: 'parker-lewis', name: 'Parker Lewis', role: 'Author, Gradually Then Suddenly', org: 'Zaprite', tags: ['Money'],
      photo: 'uploads/speakers/parker-lewis.jpg',
      x: 'https://x.com/parkeralewis',
      linkedin: 'https://www.linkedin.com/in/parker-lewis-ab904669/',
      bio: 'One of the most consistent intellectual voices on bitcoin as monetary infrastructure. Author of the "Gradually, Then Suddenly" essay series — the book the rest of bitcoin keeps catching up to. Head of Business Development at Zaprite.',
      talk: 'Imagine IF… every saver became a builder.' },
    { id: 'andre-neves', name: 'Andre Neves', role: 'CTO & Co-Founder', org: 'ZBD', tags: ['Money'],
      photo: 'uploads/speakers/andre-neves.jpg',
      x: 'https://x.com/andreneves',
      linkedin: 'https://www.linkedin.com/in/andrerfneves',
      bio: 'CTO and co-founder of ZBD. Co-author of the Lightning Address protocol — the email-style identifier that lets anyone send and receive bitcoin without a wallet address. Building the rails that make bitcoin payments feel like the internet.',
      talk: 'Imagine IF… bitcoin felt as easy as email.' },
    { id: 'candice-mcqueen', name: 'Dr. Candice McQueen', role: 'President', org: 'Lipscomb University', tags: ['Humanity', 'Intelligence'],
      photo: 'uploads/speakers/candice-mcqueen.jpg',
      bio: 'President of Lipscomb University and former Tennessee Commissioner of Education. She has led from classrooms to higher education, state government, and national nonprofit work — building institutions around teaching excellence and the next generation of leaders.',
      talk: 'Imagine IF… education formed builders.' },
    { id: 'rapha-zagury', name: 'Rapha Zagury', role: 'CEO', org: 'Twenty One Capital', tags: ['Money'],
      photo: 'uploads/speakers/rapha-zagury.jpg?v=2',
      x: 'https://x.com/RaphaZagury',
      linkedin: 'https://www.linkedin.com/in/rzagury/',
      bio: 'Zagury is a builder and coder with a deep financial background. Before becoming CEO of Twenty One Capital, he founded Elektron and held senior roles at Goldman Sachs, Merrill Lynch, and Deutsche Bank. He is a longtime Bitcoiner and sound-money advocate and has become one of the more thoughtful voices in the institutional Bitcoin conversation.\n\nHe earned his MBA from Yale. He grew up in Rio de Janeiro, began his career in New York, and now splits his time between Rio and Miami. He lives with his wife and two children and is an avid triathlete and endurance sports enthusiast.',
      talk: 'Imagine IF… every balance sheet was denominated in bitcoin.' },
    { id: 'chuck-fleischmann', name: 'Chuck Fleischmann', role: 'U.S. Congressman', org: "Tennessee's 3rd District", tags: ['Humanity', 'Freedom Tech'], featured: true,
      photo: 'uploads/speakers/chuck-fleischmann.png',
      x: 'https://x.com/RepChuck',
      bio: "Congressman Chuck Fleischmann represents Tennessee's 3rd District in the U.S. House of Representatives. He chairs the House Appropriations Subcommittee on Energy and Water Development and serves on the House Committee on Science, Space, and Technology, including the Energy Subcommittee. His district includes Oak Ridge National Laboratory and Y-12, placing him at the center of federal energy, nuclear security, and national-lab funding.",
      talk: 'Imagine IF… America went nuclear again.' },
    { id: 'paul-itoi', name: 'Paul Itoi', role: 'Founder & CEO', org: 'Stakwork', tags: ['Intelligence', 'Money'],
      photo: 'uploads/speakers/paul-itoi.png',
      x: 'https://x.com/paulitoi',
      bio: 'Founder and CEO of Stakwork — workflows where AI and humans split the work and get paid in bitcoin over Lightning. A driving force behind Sphinx, the open-source Lightning-powered communications platform. Tech entrepreneur since the mid-nineties, now building at the Bitcoin × AI frontier.',
      talk: 'Imagine IF… anyone, anywhere could earn in seconds.' },
    { id: 'adam-sullivan', name: 'Adam Sullivan', role: 'CEO', org: 'Core Scientific', tags: ['Money', 'Intelligence'],
      photo: 'uploads/speakers/adam-sullivan.webp',
      x: 'https://x.com/_Adam_Sullivan1',
      bio: 'Took the helm of Core Scientific in the depths of Chapter 11 and led it out — back onto NASDAQ and into some of the largest AI compute deals ever signed. Former digital-assets investment banker now running one of the biggest data center operators in North America, where bitcoin mining and high-performance compute share the grid.',
      talk: 'Imagine IF… the comeback was bigger than the crash.' },
    { id: 'michael-goldstein', name: 'Michael Goldstein', role: 'President', org: 'Satoshi Nakamoto Institute', tags: ['Money', 'Freedom Tech'],
      photo: 'uploads/speakers/michael-goldstein.jpg',
      x: 'https://x.com/bitstein',
      bio: 'President of the Satoshi Nakamoto Institute — keeper of bitcoin\'s primary-source literature, from the cypherpunk canon to Satoshi\'s own words. Austin-based educator on the history, technology, and economics of bitcoin, and one of its sharpest memetic minds.',
      talk: 'Imagine IF… everyone read the source material.' },
    { id: 'jesse-posner', name: 'Jesse Posner', role: 'Co-Founder', org: 'Vora', tags: ['Money', 'Freedom Tech'],
      photo: 'uploads/speakers/jesse-posner.jpg',
      x: 'https://x.com/jesseposner',
      linkedin: 'https://www.linkedin.com/in/jesseposner/',
      bio: 'Cryptography engineer behind the first BIP-340-compatible implementation of FROST — threshold signatures that let a group hold bitcoin keys with no single point of failure. Built key management and cold storage at Coinbase and Block; now co-founder of Vora, working on self-custody for your money, your data, and your AI.',
      talk: 'Imagine IF… you held the keys to everything.' },
    { id: 'jonathan-kirkwood', name: 'Jonathan Kirkwood', role: 'Co-founder and Managing Partner', org: 'Ten31', tags: ['Money', 'Intelligence'],
      photo: 'uploads/speakers/jonathan-kirkwood.png',
      photoPos: 'center 35%',
      linkedin: 'https://www.linkedin.com/in/jonathan-kirkwood-md-mba-863497253/',
      bio: 'Jonathan Kirkwood, MD MBA, is co-founder and managing partner of Ten31, where he leads capital formation and fund management. Since 2020, Ten31 has invested at the convergence of finite money and abundant intelligence: bitcoin, which is enforced by energy, and AI, which is enabled by energy. Both compound demand for the same physical infrastructure, and value gravitates to whatever stays finite. Ten31 financed bitcoin\'s plumbing and the energy-intensive compute buildout years before the trade was fashionable. In 2023, he told Forbes rackspace demand would rise a thousandfold over the decade. He is lead director at Fold Holdings (NASDAQ: FLD) and sits on the boards of Start9 Labs and Battery Finance.\n\nWhen everyone rents the same intelligence, everyone arrives at the same answer, so the durable asset is not capability but judgment, held privately and compounded over time. At personaldatacenter.xyz he documented what owning that stack actually takes: a Start9 server running StartOS, two NVIDIA DGX Sparks, open-source models fine-tuned for his needs, agents on schedule, and services reachable from the open internet without exposing personal identification. He covers how he uses the different tiers of AI, and why inference, storage, and identity are moving back inside the walls.',
      talk: 'Imagine IF… everyone owned their intelligence stack.' },
    { id: 'matt-schultz', name: 'Matt Schultz', role: 'CEO', org: 'CleanSpark', tags: ['Money', 'Humanity'],
      photo: 'uploads/speakers/matt-schultz.jpg',
      linkedin: 'https://www.linkedin.com/in/s-matthew-schultz-19400447/',
      bio: 'Co-founder, executive chairman, and CEO of CleanSpark (CLSK). Took the company from patented biomass gasifiers to microgrids at Camp Pendleton to one of the largest bitcoin mining operations in North America — raising over a billion dollars along the way. Spoke at Imagine IF 2025 alongside Sen. Marsha Blackburn on why first principles still matter in the digital world.',
      talk: 'Imagine IF… clean energy secured sound money.' },
    { id: 'rob-hamilton', name: 'Rob Hamilton', role: 'Co-Founder & CEO', org: 'AnchorWatch', tags: ['Money', 'Freedom Tech'],
      photo: 'uploads/speakers/rob-hamilton.jpg',
      x: 'https://x.com/Rob1Ham',
      linkedin: 'https://www.linkedin.com/in/anchorwatch-rob/',
      bio: 'Co-founder and CEO of AnchorWatch, the Nashville company insuring bitcoin in multisig custody with binding authority from Lloyd\'s of London — regulated insurance for keys you still hold yourself. Former IBM data scientist who led machine learning initiatives for Watson Advertising.',
      talk: 'Imagine IF… your bitcoin was insured and still yours.' },
    { id: 'rene-angel', name: 'René Ángel', role: 'Head of AI', org: 'The Reynolds Foundation', tags: ['Intelligence', 'Freedom Tech'],
      photo: 'uploads/speakers/rene-angel.jpg',
      bio: 'Head of AI at The Reynolds Foundation, a private foundation funding freedom and democracy work in more than 45 countries. He built the AI systems behind the foundation\'s grantmaking, and judged AI Hack for Freedom II at Bitcoin Park in Nashville.',
      talk: 'Imagine IF… AI worked for freedom.' },
    { id: 'jasmine-burgess', name: 'Jasmine Burgess', role: 'Chief Risk Officer', org: 'Blockstream Capital Partners', tags: ['Money', 'Freedom Tech'],
      photo: 'uploads/speakers/jasmine-burgess.jpg',
      linkedin: 'https://www.linkedin.com/in/jasmine-burgess-a3924412/',
      bio: 'Chief Risk Officer at Blockstream Capital Partners. A technology builder and risk executive, she previously served as COO/CRO and a founding executive team member at Coinbase Asset Management, where she led tokenization initiatives, built the Coinbase SMA platform, and led CBAM fund launches. She also helped launch Coremont and held CRO and senior risk roles at Brevan Howard, Prologue Capital, and Macquarie Bank after beginning her career as a credit derivatives quant at Deutsche Bank.',
      talk: 'Imagine IF… capital markets met bitcoin\'s first principles.' },
    { id: 'justin-maierhofer', name: 'Justin Maierhofer', role: 'Senior Vice President of Government Affairs', org: 'Tennessee Electric Cooperative Association', tags: ['Humanity', 'Freedom Tech'],
      photo: 'uploads/speakers/justin-maierhofer.jpg',
      photoPos: 'center 20%',
      linkedin: 'https://www.linkedin.com/in/jmaierhofer/',
      bio: 'Senior Vice President of Government Affairs at the Tennessee Electric Cooperative Association, where he leads government relations strategy for consumer-owned electric cooperatives across Tennessee. He brings more than 25 years of experience in government relations and public affairs, including more than two decades at the Tennessee Valley Authority in senior external affairs, government relations, and chief-of-staff roles. Earlier in his career, he served as a senior policy advisor at the U.S. Department of Energy and held senior roles with the Republican National Committee and the Georgia Manufactured Housing Association.',
      talk: 'Imagine IF… Tennessee powered the next buildout.' },
    { id: 'braden-stover', name: 'Braden Stover', role: 'Senior Advisor to the Commissioner, Nuclear & Quantum Strategy', org: 'Tennessee Department of Economic and Community Development', tags: ['Humanity', 'Intelligence'],
      photo: 'uploads/speakers/braden-stover.jpg',
      bio: 'Senior Advisor for Nuclear and Quantum Strategy at the Tennessee Department of Economic and Community Development. He leads statewide initiatives to position Tennessee as a national leader in advanced energy and next-generation computing, developing strategies across nuclear technology innovation, quantum research and network deployment, workforce development, regional innovation clusters, and investment attraction. Before joining TNECD, he held policy and legislative roles in the Tennessee State Senate, the U.S. House of Representatives, and the U.S. Senate.',
      talk: 'Imagine IF… Tennessee became the frontier for atoms and qubits.' },
    { id: 'javier-el-hage', name: 'Javier El-Hage', role: 'Chief Legal and Policy Officer', org: 'Human Rights Foundation', tags: ['Freedom Tech', 'Money'],
      photo: 'uploads/speakers/javier-el-hage.jpg',
      linkedin: 'https://www.linkedin.com/in/carlos-javier-el-hage-guaristi/',
      bio: 'Chief Legal and Policy Officer at the Human Rights Foundation, where he co-leads the organization\'s impact litigation and research programs. A Bolivian-born New York attorney, he works across corporate, financial, and international human rights law. His academic work includes research at the intersection of finance, technology, and international human rights, including writing on ESG disclosure and misleading ratings.',
      talk: 'Imagine IF… law defended financial freedom.' },
    { id: 'farida-nabourema', name: 'Farida Nabourema', role: 'Founder', org: 'Africa Bitcoin Conference', tags: ['Money', 'Freedom Tech'],
      photo: 'uploads/speakers/farida-nabourema.png',
      bio: 'Togolese human rights advocate and writer who has fought for democracy in Togo since she was a teenager. Founder of the Faure Must Go movement and the Africa Bitcoin Conference, she connects civil resistance, financial freedom, and bitcoin adoption across the continent.',
      talk: 'Imagine IF… money gave dissidents a way to keep moving.' },
    { id: 'felix-maradiaga', name: 'Félix Maradiaga', role: 'Pro-democracy Advocate', org: 'Nicaragua', tags: ['Freedom Tech', 'Money'],
      photo: 'uploads/speakers/felix-maradiaga.png',
      bio: 'Nicaraguan academic, pro-democracy advocate, and former prisoner of conscience. A former presidential pre-candidate and secretary general of Nicaragua\'s Ministry of Defense, Félix has spent decades building civil-society institutions and exposing how authoritarian regimes use law, finance, and technology to silence dissent.',
      talk: 'Imagine IF… financial rails could not be turned against conscience.' },
    { id: 'dhruv-bansal', name: 'Dhruv Bansal', role: 'Co-Founder & CSO', org: 'Unchained', tags: ['Money', 'Intelligence'],
      photo: 'uploads/speakers/dhruv-bansal.jpg',
      linkedin: 'https://www.linkedin.com/in/dhruvbansal/',
      bio: 'Co-founder and Chief Strategy Officer of Unchained, working where math, models, bitcoin infrastructure, and long-term thinking meet.',
      talk: 'Imagine IF… self-custody became the default for builders.' },
    { id: 'janet-rehberg', name: 'Janet Rehberg', role: 'President & CEO', org: 'EPB in Chattanooga', tags: ['Humanity', 'Intelligence'],
      photo: 'uploads/speakers/janet-rehberg.png',
      linkedin: 'https://www.linkedin.com/in/janet-rehberg/',
      bio: 'President & CEO of EPB in Chattanooga — the first woman to lead the organization in its 90-year history — bringing more than two decades of engineering, operational, and strategic leadership across power, connectivity, and civic infrastructure.',
      talk: 'Imagine IF… local infrastructure became a platform for abundance.' },
    { id: 'shaun-gleason', name: 'Dr. Shaun S. Gleason', role: 'Director of Partnerships', org: 'Oak Ridge National Laboratory', tags: ['Humanity', 'Intelligence'],
      photo: 'uploads/speakers/shaun-gleason.jpg?v=2',
      photoPos: 'center 20%',
      linkedin: 'https://www.linkedin.com/in/shaun-gleason-503bb49/',
      bio: 'Director of Partnerships at Oak Ridge National Laboratory, responsible for technology transfer, commercialization, economic development, industry partnerships, and research security. He brings decades of R&D leadership across computing, national security, cyber resilience, machine learning, and science-to-market strategy.',
      talk: 'Imagine IF… national labs moved at startup speed.' },
    { id: 'nick-elliot', name: 'Nick Elliot', role: 'Director of Government Affairs', org: 'Innovation Council Action', tags: ['Freedom Tech', 'Money'],
      photo: 'uploads/speakers/nick-elliot.png',
      bio: 'Government affairs and digital-assets policy professional working at the intersection of innovation, public policy, and the institutions shaping America\'s technology future.',
      talk: 'Imagine IF… policy kept pace with permissionless innovation.' },
    { id: 'lorenzo-valente', name: 'Lorenzo Valente', role: 'Director of Research, Digital Assets', org: 'ARK Invest', tags: ['Money', 'Intelligence'],
      photo: 'uploads/speakers/lorenzo-valente.jpg?v=2',
      x: 'https://x.com/LorenzoARK',
      linkedin: 'https://www.linkedin.com/in/lorenzo-valente-71308512a/',
      bio: 'Director of Research for digital assets at ARK Invest, focused on bitcoin, public markets, and the investment implications of open monetary networks.',
      talk: 'Imagine IF… capital markets understood digital assets at first principles.' },
  ],

  sponsors: {
    presenting: [
      { name: 'Human Rights Foundation', short: 'HRF', url: 'https://hrf.org' },
    ],
    founding: [
      { name: 'Unchained', url: 'https://unchained.com' },
      { name: 'Fedi', url: 'https://www.fedi.xyz' },
      { name: 'Foundry', url: 'https://www.foundrydigital.com' },
    ],
    pillar: [
      { name: 'ARK Invest', url: 'https://www.ark-invest.com' },
      { name: 'Cholla Inc.', url: 'https://chollainc.com' },
      { name: 'CleanSpark', url: 'https://www.cleanspark.com' },
      { name: 'Proto', url: 'https://proto.xyz/' },
    ],
    supporting: [
      { name: 'Athena', url: 'https://www.athena.com/' },
      { name: 'Bitkey', url: 'https://bitkey.world' },
      { name: 'BLISS', url: 'https://www.blissmakers.org/' },
      { name: 'Demo Lab', url: 'https://www.demolabcr.org/' },
      { name: 'Howden', url: 'https://www.howdengroupholdings.com/' },
      { name: 'Institute for Humane Studies', short: 'IHS', url: 'https://theihs.org/' },
      { name: 'The Reynolds Foundation', url: 'https://www.reynoldsfoundation.com/' },
    ],
  },

  // Agenda — not yet public. Will be added closer to the event.
  agenda: [],

  // Imagine IF 2025 archive — full YouTube playlist (PL2L0KLglmktkV95Iv6SAis4DsqoIROzJz)
  // Each talk: ten minutes, one idea. Thumbnails from img.youtube.com.
  // Order: Master-to-Student fireside (Cathie + Laffer) → all "Imagine IF" titled talks → rest.
  pastTalks: [
    // Master to Student first
    { year: '2025', videoId: 'JLcRUS-a4_g', title: 'Master to Student, the Supply Side Economy', speakers: 'Cathie Wood & Dr. Art Laffer' },

    // "Imagine IF…" titled talks
    { year: '2025', videoId: 'MCU81VGn2Kw', title: "Imagine IF We Didn't Fear Innovation", speakers: 'Troy Cross' },
    { year: '2025', videoId: 'YE6Ck4eKgp4', title: 'Imagine IF America Leads', speakers: 'Rod Roudi & Tennessee AG Jonathan Skrmetti' },
    { year: '2025', videoId: '3QpPva8ygAU', title: "Imagine IF the American Nuclear Renaissance Isn't Just a Talking Point", speakers: '' },
    { year: '2025', videoId: 'ksXNu8tKm1A', title: 'ImagineIF: The Summit of Summits', speakers: '' },

    // Rest of the archive
    { year: '2025', videoId: '6bbtHYft7t8', title: 'Bitcoin Brainstorm', speakers: 'Cathie Wood, Sen. Bill Hagerty, Dr. Laffer, Rod Roudi, Odell, & Harry Sudock' },
    { year: '2025', videoId: '0PtYdjSXMFI', title: 'The Sovereign Yield Curve: Bitcoin, Bonds, and a New Credit Paradigm', speakers: '' },
    { year: '2025', videoId: 'xfqFS-IVOog', title: 'Super Collateral for a Compute Based World: Bitcoin, AI, and Energy', speakers: 'Grant Gilliam & Sean Bill' },
    { year: '2025', videoId: 'apvU3H4IUMs', title: 'What Proof of Work Proves', speakers: 'Parker Lewis & Rapha Zagury' },
    { year: '2025', videoId: '9b-H7FFzayE', title: 'Heat as Freedom Technology: Decentralizing Mining Through Energy Use', speakers: 'Tyler Stevens' },
    { year: '2025', videoId: 'T7IbOJQ-kes', title: 'Does Cypherpunk Scale? (Does It Have To?)', speakers: 'Ryan Gentry, Jay Beddict, D++, & Uncle Rockstar Dev' },
    { year: '2025', videoId: 'uv_lWfRE-wo', title: 'How Do You Hold the Revolution?', speakers: 'Stephan Livera & Joe Kelly' },
    { year: '2025', videoId: 'LMypUHKirTI', title: 'Winning the Race for Freedom: Geopolitics in the Age of Digital Disruption', speakers: 'Matt Pines' },
    { year: '2025', videoId: 'NPGF-X1qY44', title: '2140: What Changes? What Stays the Same?', speakers: 'Michael Goldstein & Adam Back' },
    { year: '2025', videoId: 'hByt68km8C4', title: 'No Innovation is an Island', speakers: 'Robert Warren, Skot9000, Brady Cuddy, & Philip Walton' },
    { year: '2025', videoId: 'ZkYSy5y39cE', title: 'Why First Principles Still Matter in the Digital World', speakers: 'Matt Schulz & Sen. Marsha Blackburn' },
    { year: '2025', videoId: 'LyBrvnwARlk', title: 'Freedom of Thought in the Age of AI', speakers: 'Mark Suman' },
    { year: '2025', videoId: 'nW_3jppA9nQ', title: "The Emergent Grid: Lessons From Africa for America's Energy Future", speakers: 'Erik Hersman' },
    { year: '2025', videoId: 'qvTx84brNt0', title: 'Closing Panel', speakers: 'Rod Roudi, Robert Warren, D++, & Anna Checkhovich' },
    { year: '2025', videoId: 'rFV8CfFF5kg', title: 'Trust Nobody, Ever Again — Building a Modular Future', speakers: 'John Arnold, Max Kei, & Rory Murray' },
    { year: '2025', videoId: '7eFb7AQla_k', title: 'Making Freedom Profitable', speakers: 'Matt Odell' },
    { year: '2025', videoId: 'Rs1y1gEAwNU', title: 'Energy as a Balance Sheet', speakers: 'Robert Warren & Adam Sullivan' },
    { year: '2025', videoId: 'NObq313h0hc', title: 'Bitcoin as Constitutional Order: Stories that Become States', speakers: 'Jonathan Kirkwood & Brian Domitrovic' },
    { year: '2025', videoId: 'URbBq6C4PE8', title: 'Local Power, Global Fuel: Securing Energy Independence', speakers: '' },
    { year: '2025', videoId: 'V-f8JFhbW4E', title: 'The Frontier Playbook for Ambition', speakers: 'Harry Sudock' },
    { year: '2025', videoId: '4OZcEgX4ZvE', title: 'Welcome to Nashville + Partnership 2030', speakers: '' },
    { year: '2025', videoId: 'B90AG3sHJ2E', title: 'Speed to Scale and the New Era of Compute', speakers: 'Harry Sudock, Adam Sullivan, & Kara Sutton' },
    { year: '2025', videoId: 'hfXUwuH2OPU', title: 'Freedom Tech is Fundamental to a Free Society', speakers: 'Econoalchemist' },
    { year: '2025', videoId: 'kbMfJtEHHLQ', title: 'Open Communities in the Age of Control', speakers: 'Matt Odell, Derek Ross, & Shawn Yeager' },
  ],
};
